---
title: "Jasmine Ho Qiu's resume"
author: Jasmine Ho Qiu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> jasmineqiu0@gmail.com
- <i class="fa fa-github"></i> [github.com/Jasminni3](https://github.com/Jasminni3)
- <i class="fa fa-phone"></i> +1 510 598 7503
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------
- Technical: Google Workspace (Docs, Sheets, Slides), Microsoft 365 (Word, Excel, PowerPoint), Canva, Stata, R, Python, QuickBooks 

- Expertise: Project Management, Market Research, Financial Analysis, Data Analysis, Consulting


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Jasmine Ho Qiu {#title}
--------------------------------------------------------------------------------

### Aspiring Business Professional

An aspiring business student with a focus on entry-level business roles and data analysis. Dedicated to applying academic knowledge and analytical skills to contribute effectively in dynamic organizational environments. Committed to leveraging data-driven insights to inform strategic decision-making and drive innovation.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### University of California: San Diego

B.S. in Business Economics; Minor in Finance

San Diego, CA

2024

Professional Expereience {data-icon=laptop}
--------------------------------------------------------------------------------

### Critical Thinking Game Designer

Lirvana Labs (Learning Companion App)  

Menlo Park, CA 

October 2023 – 
     
-Helping to build an interactive, AI learning app for children globally (Thailand, Hong Kong, and Virginia) on a 7-member team

-Implementing social-emotional learning models, laying the groundwork for the app's deployment in educational institutions around the world

-Presenting the application of AI in education at the ASU+GSV AIR SHOW, delivering an impactful talk to a diverse audience of 50+ professionals

### Lead Instructor

TechKnowHow (Summer Tech Camp) 

Oakland, CA    

June 2023 - August 2023

-Taught 20 students innovation utilizing LEGO building blocks and Scratch programming by creating engaging lesson plans and cultivating a supportive learning environment

-Applied age-appropriate teaching methods to accommodate students’ diverse learning styles while still aligning with set curriculum objectives 

-Leveraged problem-solving skills to address and resolve classroom or personal conflicts to ensure a safe and enriching summer camp experience for all students

### People and Culture Intern  

GRID Alternatives (Renewable Energy Firm)

San Diego, CA 

June 2022 - August 2022

-Conducted a comprehensive analysis of quantitative DEI data collected over 8 years to streamline and establish clear and transparent company metrics to define the upcoming fiscal year’s goals for all stakeholders

-Collaborated with a team of 4 executives to strategize and implement innovative DEI initiatives, focused on copy-writing and having a progressive approach to implement a new maternity policy maternity policy

### Project Management Analyst Intern	

StarGazer Enterprise (Consulting Firm)

Oakland, CA

August 2020 - October 2020

-Organized and recorded company-wide financial transactions to ensure the accuracy of accounts payable and accounts receivables on QuickBooks

-Conducted extensive market research on the background and actions of the BART Measure RR Oversight Committee

### Junior Consultant

Banteay Srei (Social Advocacy Organization)

Oakland, CA

September 2018 - July 2020

-Developed a community action project by acquiring donations via fundraising, resulting in 50+ free feminine hygiene kits for homeless women in underserved neighborhoods

-Created weekly workshops with PowerPoint, and led discussions on various topics centered around women's empowerment (ex: Self Defense, Reproductive Rights, Conflict Mediation) to an audience of 30+ students


